---
- name: Deploy container ELK Stack 
  hosts: ELK

  tasks:
    - name: Upgrade RHEL Family OS packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes