---
- name: Upgrade and Reboot RHEL and install docker
  hosts: all
  vars_files:
    - vars/vars.yml
  vars:
    - reboot_connect_timeout: 5
    - reboot_post_reboot_delay: 15
    - reboot_timeout: 600

  tasks:
    - name: Upgrade RHEL Family OS packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes

    - name: Disable SELinux
      selinux:
        state: disabled

    # # Reboot after upgrade
    # - name: Reboot host
    #   reboot:
    #     connect_timeout: "{{ reboot_connect_timeout }}"
    #     post_reboot_delay: "{{ reboot_post_reboot_delay }}"
    #     reboot_timeout: "{{ reboot_timeout }}"  

    # Install docker Redhat or CentOS
    - name: Install docker Redhat or CentOS
      yum:
        name: "{{item}}"
        state: latest
      loop: "{{ docker_package_vars }}"

    - name: "Configuring docker-ce repo"
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644

    - name: " Installing Docker latest version"
      yum:
        name: docker-ce
        state: present
      
    - name: " Starting and Enabling Docker service"
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_check
      ignore_errors: yes

    - name: Download and install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 0755
      when:
        - docker_compose_check.msg is defined
        - docker_compose_check.msg.find('No such file or directory') != -1

    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes

    - name: Set timezone to Asia/Bangkok
      timezone:
        name: Asia/Bangkok

    - name: Add net.ipv4.ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: Add or modify hard nofile limits for wildcard domain
      community.general.pam_limits:
        domain: '*'
        limit_type: hard
        limit_item: nofile
        value: 65535

    - name: Add or modify soft nofile limits for wildcard domain
      community.general.pam_limits:
        domain: '*'
        limit_type: soft
        limit_item: nofile
        value: 65535
